---
- name: Generate docker-compose.yml from template
  template:
    src: templates/docker-compose.j2
    dest: /opt/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  when: modules_to_deploy | length > 0

- name: Validate docker-compose.yml syntax
  command: docker-compose -f /opt/docker-compose.yml config
  register: compose_validation
  changed_when: false
  ignore_errors: true
  when: modules_to_deploy | length > 0

- name: Show validation errors if any
  debug:
    msg: "{{ compose_validation.stderr }}"
  when: (modules_to_deploy | length > 0) and (compose_validation.rc != 0)

- name: Fail if docker-compose.yml is invalid
  fail:
    msg: "docker-compose.yml validation failed, see previous error."
  when: (modules_to_deploy | length > 0) and (compose_validation.rc != 0)

- name: Deploy or restart modules with Docker Compose
  community.docker.docker_compose:
    project_src: /opt
    pull: yes
    project_name: "{{ project_name }}"
    recreate: always
    scale: "{{ modules_to_deploy | items2dict(key_name='name', value_name='replicas') }}"
  when: (modules_to_deploy | length > 0) and (compose_validation.rc == 0)



