---
- name: Afficher les modules
  debug:
    var: modules

- name: Afficher les secrets
  debug:
    var: secrets

- name: Ensure Docker is installed
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

# Connexion au GitHub Container Registry
- name: Log in to GitHub Container Registry
  docker_login:
    registry_url: ghcr.io
    username: "{{ github_username }}"
    password: "{{ github_token }}"

- name: Create Docker networks
  docker_network:
    name: "{{ item }}"
    state: present
  loop: "{{ modules | map(attribute='networks') | flatten | unique }}"
  when: item is defined

- name: Get current container versions
  community.docker.docker_container_info:
    name: "{{ project_name }}_{{ item.name }}_1"
  register: container_versions
  loop: "{{ modules }}"

- name: Debug des images des containers
  debug:
    msg: "{{ container_versions.results | map(attribute='container.Config.Image', default='N/A') | list }}"

- name: Extraire la liste des images des containers
  set_fact:
    container_images_list: >-
      {{
        container_versions.results
        | selectattr('container.Config', 'defined')
        | selectattr('container.Config.Image', 'defined')
        | map(attribute='container.Config.Image')
        | list
      }}

- name: Debug container_images_list
  debug:
    var: container_images_list

- name: Filtrer les modules à installer ou redémarrer (sans doublons)
  set_fact:
    modules_to_deploy: >-
      {{
        (
          modules | rejectattr('image', 'in', container_images_list)
                  + 
          modules | selectattr('force_restart', 'equalto', true)
        ) | unique(attribute='name') | list
      }}

- name: Valider qu'il n'y a pas de doublons
  assert:
    that:
      - modules_to_deploy | map(attribute='name') | list == (modules_to_deploy | map(attribute='name') | unique | list)
    fail_msg: "ERREUR : Doublons détectés dans modules_to_deploy"


- name: Afficher les modules à déployer
  debug:
    var: modules_to_deploy

- name: Appliquer les secrets
  set_fact:
    modules_to_deploy: "{{ modules_to_deploy | inject_secrets(secrets) }}"

- name: Afficher les modules à déployer apres mise à jour des secrets
  debug:
    var: modules_to_deploy

- name: Generate docker-compose.yml from template
  template:
    src: templates/docker-compose.j2
    dest: /opt/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Validate docker-compose.yml syntax
  command: docker-compose -f /opt/docker-compose.yml config
  register: compose_validation
  changed_when: false
  ignore_errors: true

- name: Show validation errors if any
  debug:
    msg: "{{ compose_validation.stderr }}"
  when: compose_validation.rc != 0


- name: Fail if docker-compose.yml is invalid
  fail:
    msg: "docker-compose.yml validation failed, see previous error."
  when: compose_validation.rc != 0

- name: Deploy or restart modules with Docker Compose
  community.docker.docker_compose:
    project_src: /opt
    pull: yes
    project_name: "{{ project_name }}"
    recreate: always
    scale: "{{ modules_to_deploy | items2dict(key_name='name', value_name='replicas') }}"
  when: compose_validation.rc == 0


