---
- name: Initialiser la liste transformée
  set_fact:
    secrets_summary: []

- name: Générer liste avec valeur name + clés autres champs (sans valeurs)
  set_fact:
    secrets_summary: >-
      {{
        secrets_summary | default([]) + [
          [ item.name ] +
          (item | dict2items
                | rejectattr('key', 'equalto', 'name')
                | map(attribute='key')
                | list)
        ]
      }}
  loop: "{{ secrets }}"
  when: secrets is defined and secrets | length > 0

- name: Afficher le résultat
  debug:
    var: secrets_summary
  when: secrets is defined and secrets | length > 0

# Connexion au GitHub Container Registry
- name: Log in to GitHub Container Registry
  docker_login:
    registry_url: ghcr.io
    username: "{{ github_username }}"
    password: "{{ github_token }}"

- name: Create Docker networks
  docker_network:
    name: "{{ project_name}}_{{ item }}"
    state: present
  loop: "{{ modules | map(attribute='networks') | flatten | unique }}"
  when: item is defined

- name: Appliquer les secrets
  set_fact:
    modules_to_deploy: "{{ modules_to_deploy | inject_secrets(secrets) }}"
  when: secrets is defined and secrets | length > 0

- name: Configurer docker v1
  ansible.builtin.include_tasks: docker_v1.yml
  tags: docker
  when: ansible_distribution | lower == "debian"

- name: Configurer docker v2
  ansible.builtin.include_tasks: docker_v2.yml
  tags: docker
  when: ansible_distribution | lower == "ubuntu"

- name: Aucun module installé
  debug:
    msg: "Aucun module n'est installé "
  when: modules_to_deploy | length == 0


