- name: Install my webserver
  hosts: all
  become: yes
  vars:
    workspace_root: "{{ playbook_dir }}/.."
  vars_files:
    - deployment.yml
  roles:
    - role: extra_files
    #- role: deploy

    #- role: nginx
    #  when: nginx_local.enabled | default(false)