- name: Install my webserver
  hosts: all
  become: yes
  vars:
    workspace_root: "{{ playbook_dir }}/.."
  roles:
    - role: extra_files
    - role: filter_modules
    - role: deploy
    - role: keycloak_theme
    - role: nginx
      when: nginx_local.enabled | default(false)
