version: '3.8'

services:
  adp-gateway:
    image: "ghcr.io/***/adp-gateway:1.0.71"
    restart: always
    ports:
      - "8080:8080"
      - "8081:8080"
    networks:
      - my_network
    environment:
      ENV_VAR_1: "value1"
      ENV_VAR_2: "value2"
    resources:
      limits:
        memory: "512M"
        cpus: "0.5"

networks:
  my_network:
    driver: bridge