- name: Lire la version installée pour {{ item.name }}
  shell: |
    grep '^{{ item.name }} ' {{ theme_versions_file }} | awk '{print $2}' || echo none
  register: theme_version_result
  changed_when: false

- name: Ajouter à la liste si la version diffère
  set_fact:
    themes_to_install: "{{ themes_to_install + [item] }}"
  when: theme_version_result.stdout != item.image.split(':')[-1]
