# .github/workflows/detect-environment.yml
on:
  workflow_call:
    inputs:
      deploy_release:
        description: "Environnement release demandé (manuellement)"
        required: false
        type: string
      deploy_dev:
        description: "Environnement develop demandé (manuellement)"
        required: false
        type: string
    outputs:
      environment:
        description: "Nom de l'environnement (ex: dev, prod)"
        value: ${{ jobs.detect.outputs.environment }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setenv.outputs.environment }}
    steps:
      - name: Déterminer l'environnement
        id: setenv
        env:
          IS_DISPATCH: ${{ github.event_name == 'workflow_dispatch' }}
          ENV_DEV: ${{ inputs.deploy_dev || '' }}
          ENV_RELEASE: ${{ inputs.deploy_release || '' }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [ "$IS_DISPATCH" = "true" ]; then
            if [ "$GITHUB_REF_NAME" = "develop" ]; then
              if [ -n "$ENV_DEV" ]; then
                echo "environment=$ENV_DEV" >> $GITHUB_OUTPUT
                echo "Environnement déterminé manuellement: $ENV_DEV"
              else
                echo "environment=unknown" >> $GITHUB_OUTPUT
              fi
            elif [ -n "$ENV_RELEASE" ]; then
              echo "environment=$ENV_RELEASE" >> $GITHUB_OUTPUT
              echo "Environnement déterminé manuellement: $ENV_RELEASE"
            else
              echo "environment=unknown" >> $GITHUB_OUTPUT
              echo "::error::Paramètre manquant: env_deploy est requis pour workflow_dispatch hors develop"
            fi
          else
            if [ "$GITHUB_REF_NAME" = "develop" ]; then
              if [ -n "$ENV_DEV" ]; then
                echo "environment=$ENV_DEV" >> $GITHUB_OUTPUT
                echo "Environnement déterminé manuellement: $ENV_DEV"
              else
                echo "environment=dev" >> $GITHUB_OUTPUT
                echo "Environnement déterminé (develop): dev"
              fi
            else
              echo "environment=unknown" >> $GITHUB_OUTPUT
              echo "::error::Environnement inconnu pour la branche: $GITHUB_REF_NAME"
            fi
          fi
